### ISSUE TITLE
emergency help！

### ISSUE THREAD

**Issue by xuhao0521** [alcides/GeneticEngine#154]
Author, after you update the library (add geml), all my examples will not run normally, but the previous version can run normally.

<img width="1269" alt="prob" src="https://github.com/alcides/GeneticEngine/assets/40332164/44d73254-f030-4a5c-8eda-587348c4f20e">

**Comment by alcides** [comment]
Hello. The main branch has major changes in the API. If you roll back to your latest local commit, and pull from the stable branch, everything will still work.

`git reset —hard HASHOFYOURLASTLOCALCOMMIT`
and then
`git pull origin stable`

If you just using genetic engine, a better alternative is to create a new project, and just use the stable release on pypi using:

pip install geneticengine

You do not need to edit this project directly to use. However if you are chancing GenenticEngine, maybe working on your own branch and pull from stable is better. Regardless, feel free to reach out and I can help with all the migrations.

**Comment by xuhao0521** [comment]
@alcides Thank you for your enthusiastic and timely help. Without a doubt, the Genetic Engine is a great job！
