### ISSUE TITLE
Error when missing @dataclass

### ISSUE THREAD

**Issue by Leoningel** [alcides/GeneticEngine#38]

**Comment by alcides** [comment]
Need more details on this issue.

**Comment by Leoningel** [comment]
When defining a grammar, each node should either be abstract or have an init function specialised to the class, which we make through the dataclass decorator. If we define a grammar with a node that isn't either abstract nor has an init function, it should give an error. I was trying to implement it but failed as the nodes always have an init function. How do we check that each node is either abstract or has a specialised init function?

**Comment by alcides** [comment]
Just to clarify: 

```
class Leaf:
  pass
```

Is a valid node. The only case that should fails is when there are arguments, but those arguments have no declared type.

**Comment by Leoningel** [comment]
Thanks for the clarification! 

I just tried removing the dataclass from MatrixElement in examples/game_of_life.py and I still don't get a self-explanatory error. This issue is thus not fixed.

**Comment by alcides** [comment]
Removing data class from that class is not an error. It will simply ignore the annotated fields, and they'll be left with None. 
But that's okay, because users might want to do that for another purpose (not that there's an __init__ constructor still, just doesn't receive any parameters).

**Comment by Leoningel** [comment]
I understand what you're saying. The error is obtained in the evolutional process. Did you see the error and do you agree with me that this error is unsatisfying? I've already had this error a couple of times and it takes a lot of time to get through. Maybe a warning a grammar processing would do.

**Comment by Leoningel** [comment]
It still doesn't work for the example where I take out @dataclass from MatrixElement in the game_of_life.py example

**Comment by Leoningel** [comment]
No it didn't. I also checked and the if statement for the warning is not
triggered

**Comment by Leoningel** [comment]
Fixed
