### ISSUE TITLE
Parallel evaluation

### ISSUE THREAD

**Issue by Leoningel** [alcides/GeneticEngine#40]

**Comment by alcides** [comment]
Parallel evaluation is already in main, and True as default. Is this working for everyone?

**Comment by Leoningel** [comment]
Are you sure it is? I reverted the pull request as it gave issues when running. Also, when I look in gp.py and search for parallel evaluation, I don't find anything.

**Comment by alcides** [comment]
Could you checkout the parallel_evaluation branch and report the issues that you had?

Tests and examples are working fine on my machine. Make sure to reinstall all dependencies in this new branch.

**Comment by Leoningel** [comment]
To be honest, I cannot get a clear error message (as I cannot get the terminal to stop) except this one: 
![image](https://user-images.githubusercontent.com/74727390/166897617-bb57a0ae-8cfa-4dc9-aded-4b6a923706ba.png)

**Comment by alcides** [comment]
Seems like a windows-specific issue. We can address tomorrow in our weekly meeting.

**Comment by Leoningel** [comment]
Sounds good!
