### ISSUE TITLE
CSV Callback doesn't allow for restarting evolution

### ISSUE THREAD

**Issue by Leoningel** [alcides/GeneticEngine#42]
Sometimes it is convenient to run an evolution in different parts, using the same GP object (for example with grid search). When doing so, the CSV Callback closes the csv writing connection after the first evolution, making further usage impossible. It should work again when the new evolution starts.

**Comment by alcides** [comment]
I think it's a bad policy to re-use the same callbacks for multiple evolution processes. That will cause problems if you want multiple evolutions in parallel.

Is this issue about the callbacks being parameters of the constructors and not the evolve?

**Comment by Leoningel** [comment]
Well I think you should be able to split up an evolution process in multiple parts. For example, I run my evolution for 100 generations, then I update the population in some way, and I continue the process.

I think it can be fixed by making the the callback parameters of the evolve. The csv should not be overwritten after each evolutional process.

**Comment by Leoningel** [comment]
I don't understand the first solution. The second would work for this specific example, but when doing cross validation, it wouldn't work!

**Comment by Leoningel** [comment]
You're completely right. 

Sounds like a good solution.

**Comment by Leoningel** [comment]
It is not yet implemented as such. The population is currently initialised at the beginning of evolve, allowing for reusing the object. I agree with you that it shouldn't be like that and that cross-validation should use different objects.

The solution looks good. Would directly calling the GP without the "with" statement still work?

**Comment by alcides** [comment]
The with is not implemented. If we go that route, it will not work without the with (or other method calls, like exit). Your opinion @GUIpsp ?

Now regarding the cross-validation, it is something you can change without changing GeneticEngine.


One decision we could take is to divide evolve() into initialize() and iterate() (a single generation). That the user could call directly. I believe the callback approach to be much better.

**Comment by Leoningel** [comment]
Thanks

**Comment by Leoningel** [comment]
Let's not implement this anymore, doesn't seem relevant.
