### ISSUE TITLE
Is_terminal recognises lists as terminal even when they are not terminals

### ISSUE THREAD

**Issue by Leoningel** [alcides/GeneticEngine#43]
The function is_terminal in geneticengine.core.utils.py recognises lists as terminals, even though they aren't necessarily terminals. In our examples they are never terminals. For now I fixed it by making sure lists are not taken into account at the places where it mattered in [this](https://github.com/alcides/GeneticEngine/commit/d5a11021d6ad9387a714a545c8b708094b8bac66) commit and separately handled lists in a correct way in these ([grammar (is the fix necessary here? It currently doesn't do anything)](https://github.com/alcides/GeneticEngine/commit/103451b850b266f994f2b6e590ce01fde55c388e), [and relabel_nodes](https://github.com/alcides/GeneticEngine/commit/7737da19dfebb89cd80e0ea95cb76228e5d0abe4)) commits. To do this all, I had to [change](https://github.com/alcides/GeneticEngine/commit/8523ec5c7935a0eac1fc6a3593c70326bfbe6054) the test files! 

Notice that with these changes lists have elements of non-terminal type! This shouldn't be the case, but as all our examples are as such, I did it this way for now.

**Comment by alcides** [comment]
Grammar-wise:

-  List[int] should not be a terminal symbol.

Tree-wise:

- [] should be a terminal.
- [1] should not be a terminal.

Maybe we should rename the functions to be more specific? is_terminal_symbol for the first and is_terminal_node for the second?

I need to inspect the code to understand which one you are talking about.

**Comment by Leoningel** [comment]
I agree

**Comment by Leoningel** [comment]
Fixed by the mighty @GUIpsp and published in [alpha20](https://github.com/alcides/GeneticEngine/releases/tag/alpha20).
